services:
  data-provider:
    build: .
    command: python -u /app/app.py
    environment:
      - DATABASE_PATH=/app/data/prices.db
      - API_PORT=8000
      # - ALLORA_VALIDATOR_API_URL=https://allora-api.testnet-1.testnet.allora.network/emissions/v1/network_loss/
      - ALLORA_VALIDATOR_API_URL=https://localhost:1317/emissions/v1/network_loss/
      - TOKEN=ETH
      - TOKEN_CG_ID=ethereum
    ports:
      - "8000:8000"
    volumes:
      - ./data-provider-data:/app/data

  data-updater:
    container_name: data-updater
    build: .
    depends_on:
      - data-provider
    entrypoint: ["sh", "-c", "while true; sleep 20; do python -u /app/update_app.py; done"]
    environment:
      - DATA_PROVIDER_API_ADDRESS=http://data-provider:8000

  reputer:
    container_name: reputer
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    depends_on:
      - data-provider
    env_file:
      - ./worker-data/env_file

volumes:
  worker-data:
  data-provider-data:
